name: humm
description: A Music Player App form local Storage.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  auto_route: ^5.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.10+1
  flutter_riverpod: ^2.0.2
  flutter_svg: ^1.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.7.0
  just_audio: ^0.9.29
  just_audio_background: ^0.0.1-beta.7
  marquee: ^2.2.3
  on_audio_query: ^2.6.1
  on_audio_room: ^2.2.1+1
  path: ^1.9.0
  path_provider: ^2.1.1
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.2
  build_runner: ^2.2.1
  hive_generator: ^1.1.3
  json_serializable: ^6.4.1

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  color_dark: "#181A20"
  image_dark: assets/images/logo.png

  android_12:
    image: assets/images/logo.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/logo.png
    icon_background_color_dark: "#181A20"

  web: false

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

  fonts:
    - family: Urbanist
      fonts:
        - asset: fonts/Urbanist-Regular.ttf
          weight: 400
        - asset: fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: fonts/Urbanist-Bold.ttf
          weight: 700
